version: '3.8'
services:
  backend:
    build: ./backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - chroma_db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

  chroma_db:
    image: chromadb/chroma:latest
    container_name: chroma-db
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    restart: unless-stopped

volumes:
  chroma_data:
